name: Build/release Electron

on:
  push:
    branches:
      - feat/github-actions-electron-workflow

env:
  GH_TOKEN: ${{ secrets.github_token }}

jobs:
  release:
    runs-on: macos-latest

    steps:
      - name: Checkout repository ðŸ›Žï¸
        uses: actions/checkout@v3

      - name: Setup Node version ðŸ€
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies âš™ï¸
        run: npm ci

      - name: Build and Signing Electron App ðŸ› ï¸
        run: |
          CSC_LINK=cert.p12
          CSC_KEY_PASSWORD=${{ secrets.CSC_KEY_PASSWORD }}
          echo ${{ secrets.MACOS_CERT_P12 }} | base64 --decode > $CSC_LINK
          npm run electron:build
          rm $CSC_LINK

      - name: Save artifacts
        uses: actions/upload-artifact@v3
        with:
          name: electron-release-app
          path: |
            release-electron/**
            !release-electron/mac-arm64
            !release-electron/mac
